CrudDjango/CrudDjango/urls.py
from django.contrib import admin
from django.urls import path
from CrudExample import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add',views.addAcc),
    path('show',views.showAcc),
    path('edit/<int:id>',views.edit),
    path('update/<int:id>',views.update),
    path('delete/<int:id>',views.delete)
]

CrudDjango/CrudExample/models.py
from django.db import models

# Create your models here.

class Account(models.Model):
    userName = models.CharField(max_length= 10)
    passwd = models.CharField(max_length= 10)
    showName = models.CharField(max_length= 30)
    email = models.CharField(max_length= 30)
    address = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)

    class Meta:  
        db_table = "Account"

CrudDjango/CrudExample/forms.py
from django import forms
from CrudExample.models import Account
    
class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = "__all__"

CrudDjango/CrudExample/views.py
from django.shortcuts import render, redirect
from CrudExample.forms import AccountForm
from CrudExample.models import Account

# Create your views here.
def addAcc(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if(form.is_valid)():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form =AccountForm()
    return render(request,'addAcc.html',{'form':form})

def showAcc(request):
    acc = Account.objects.all()
    return render(request,"index.html",{'accounts':acc})

def edit(request,id):
    account = Account.objects.get(id = id)
    return render(request,'edit.html',{'acc':account})

def update(request,id):
    account =  Account.objects.get(id = id)
    form = AccountForm(request.POST, instance = account)
    if form.is_valid():
        try:
                form.save()
                return redirect("/show")
        except:
                pass
    return render(request,'edit.html',{'acc':account})

def delete(request,id):
    account  = Account.objects.get(id = id)
    account.delete()
    return redirect("/show")

CrudDjango/CrudExample/templates/addAcc.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crud Example</title>
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
  
</head>

<body>
    <form method="POST" class="post-form" action="/add">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Username:</label>
                <div class="col-sm-4">
                    {{ form.userName}}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Password:</label>
                <div class="col-sm-4">
                    {{ form.passwd }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Email:</label>
                <div class="col-sm-4">
                    {{ form.email }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Show Name:</label>
                <div class="col-sm-4">
                    {{ form.showName }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Address:</label>
                <div class="col-sm-4">
                    {{ form.address }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Phone:</label>
                <div class="col-sm-4">
                    {{ form.phone }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

CrudDjango/CrudExample/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crud Example</title>
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    
</head>

<body>
    <form method="POST" class="post-form" action="/update/{{acc.id}}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Username:</label>
                <div class="col-sm-4">
                    <input type="text" name="acusername" id="id_username" required maxlength="20" value="{{ acc.userName }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Password:</label>
                <div class="col-sm-4">
                    <input type="text" name="acpassword" id="id_password" required maxlength="100"
                        value="{{ acc.passwd }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Show Name:</label>
                <div class="col-sm-4">
                    <input type="text" name="accshowname" id="id_showname" required maxlength="15"
                        value="{{ acc.showName }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Email:</label>
                <div class="col-sm-4">
                    <input type="email" name="accemail" id="id_email" required maxlength="254"
                        value="{{ acc.email }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Address:</label>
                <div class="col-sm-4">
                    <input type="text" name="acaddress" id="id_address" required maxlength="15"
                        value="{{ acc.address }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Phone:</label>
                <div class="col-sm-4">
                    <input type="text" name="acphone" id="id_phone" required maxlength="15"
                        value="{{ acc.phone }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

CrudDjango/CrudExample/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crud Example</title>
    {% load static %}  
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >  
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" >  
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>  
    
</head>
<body>
    <table class="table table-bordered">  
        <thead>  
        <tr>  
            <th>UserName</th>
            <th>ShowName</th>  
            <th>Email</th>  
            <th>Address</th>
            <th>Phone</th>
            <th>Actions</th>  
        </tr>  
        </thead>  
        <tbody>  
    {% for ac in accounts %}  
        <tr>  
            <td>{{ ac.userName }}</td>   
            <td>{{ ac.showName }}</td>  
            <td>{{ ac.email }}</td>  
            <td>{{ ac.address }}</td>  
            <td>{{ ac.phone }}</td> 
            <td>  
            <button type="button" class="btn"><a href="/edit/{{ ac.id }}"> <i class="fa fa-pencil-square-o" aria-hidden="true"> </i></a></button>
                
            <button type="button" class="btn"><a href="/delete/{{ ac.id }}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>  </button>
            </td>  
        </tr>  
    {% endfor %}  
        </tbody>  
    </table>  
    <br>  
    <br>  
    <a href="/add" class="btn btn-primary">Add New Record</a>
</body>
</html>